global using Nice.DTO;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Threading.Tasks;
//global using System.ComponentModel.DataAnnotations;
global using Nice.Attributes;
global using Nice.Simple.Contracts.Enums;