global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using Nice.Simple.Contracts;
global using Nice.Simple.Contracts.DTO;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Nice.Tests;